name: Release_deploy_GolangApp_Go_Fortune

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:
    runs-on:  ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:

    - name: checking version
      uses: actions/checkout@v3
      with:
        ref:  ${{ github.ref_name }}

    - name: Install node version
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install global railway
      run: npm i -g @railway/cli

    - name: release created
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version
        prev_tag: 'pkk'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITTOKEN }}


    - name: railway deploy 
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Format Json
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GDipSA55 CI/CD Assignment",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nPearl Khin Khin"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265067Y"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\ne1045742@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/Pearl-15/GoLangApp"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://golangapp-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://golangapp-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.TEST_SUBMISSION }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK